using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[ExecuteInEditMode]
public class AutoGeneratedTerrain : MonoBehaviour {

	public float xdecal = 0f;
	public float ydecal = 0f;

	// Use this for initialization
	void Start () {
		if (gameObject.GetComponent<Terrain>())
		{
			GenerateHeights(gameObject.GetComponent<Terrain>(), 10.0f);
		}
	}
	
#if UNITY_EDITOR
	void Update () {
		if (gameObject.GetComponent<Terrain>())
		{
			GenerateHeights(gameObject.GetComponent<Terrain>(), 10.0f);
		}
	}
#endif

	public void GenerateHeights(Terrain terrain, float tileSize)
	{
		float[,] heights = new float[terrain.terrainData.heightmapWidth, terrain.terrainData.heightmapHeight];
		for (int i = 0; i < terrain.terrainData.heightmapWidth; i++)
		{
			for (int k = 0; k < terrain.terrainData.heightmapHeight; k++)
			{
				float x = ((float)i / (float)terrain.terrainData.heightmapWidth) * tileSize + xdecal;
				float y = ((float)k / (float)terrain.terrainData.heightmapHeight) * tileSize + ydecal;
				heights[i, k] = Mathf.PerlinNoise(x, y)/10.0f;
			}
		}
		terrain.terrainData.SetHeights(0, 0, heights);
	}
}
